#' @title The \code{designDiagram} class and some basic methods
#'
#' @name designDiagram-class
#' @description
#' Objects of class \code{designDiagram} as generated by \code{\link{DD}} is a list with entries as specified below.
#' \describe{
#'   \item{\code{terms}}{Named vector with all terms in the design.}
#'   \item{\code{random.terms}}{Vector with the random terms in the design.}
#'   \item{\code{Nparm}}{Named vector with the number of parameters for the terms.}
#'   \item{\code{df}}{Named vector with the degrees of freedom for the terms.}
#'   \item{\code{SS}}{Named matrix with Sum-of-Squares if a response variable was specified.}
#'   \item{\code{MSS}}{Named matrix with Mean-Sum-of-Squares if a response variable was specified.}
#'   \item{\code{relations}}{Named matrix with relations between variables with the following interpretation: "0"=linear indepent, "<"=row term is a subspace of column, "<-"=row term is a subspace of column term and no other terms are inbetween, ">" and "->" the similar interpretatioin between columns and rows, name=name of minimum between row and column term.}
#'   \item{\code{pvalue}}{Named matrix with p-values for Type-I F-tests. p-values are stated at the collapsed nesting, but F-test are done against the most coarse nested random effect.}
#'   \item{\code{inner}}{Named matrix of squared inner products of subspaces with nesting subspaces removed. Rouded at 6'th digits, and used to decide orthogonality of the design.}
#'   \item{\code{response}}{Logical stating whether a response variable was present.}
#' }
#' 
#' @param x object of class \code{designDiagram}
#' @param circle character specifying which circles to draw at the terms: \code{"none"}=no circles, \code{"SS"}=a circle with area proportional to the associated Sum-of-Squares, \code{"MSS"}=a circle with area proportional to the associated Mean-Sum-of-Squares, \code{"III"}=TO BE DESCRIBED. The three latter options are only available if a response variable was specified for the design. Defaults to \code{"none"}.
#' @param pvalue boolean specifying whether p-values should be inserted on the graphs. This is only possible if a response variable was specified. Defaults to \code{TRUE} is \code{circle="MSS"} and \code{FALSE} otherwise.
#' @param kill formula specifying which cirlces not to plot. Defaults to \code{~1} corresponding to not plotting the intercept term (that otherwise may overweight the remaining terms).
#' @param ca boolean deciding whether colinearity analysis is visualized. Defauls to \code{TRUE}.
#' @param color color of circles when \code{ca=FALSE}. Defaults to \code{"lightgreen"} for Sum-of-Squares and to \code{"lightblue"} for Mean-Sum-of-Squares.
#' @param circle.scaling numeric specifying size scaling of circles. Defaults to \code{1}, which corresponds to the largest circle having a radius that is half of the shortest distance between two nodes.
#' @param arrow.type specifying arrow heads via \code{\link{arrow}}. Defaults to \code{arrow(angle=20,length=unit(4,"mm"))}.
#' @param xlim x-range of diagram plot. Defaults to \code{c(0,1)}.
#' @param ylim y-range of diagram plot. Defaults to \code{c(0,1)}.
#' @param horizontal boolen specifying if the design diagram should be drawn horizontally or vertically. Defauls to \code{TRUE}.
#' 
#' @seealso \code{\link{DD}}
#' 
#' @importFrom stats as.formula formula model.frame model.matrix model.response pf pt qt quantile r2dtable rmultinom rt terms
#' @importFrom ggplot2 unit geom_blank geom_label coord_fixed 
#' @importFrom ggraph create_layout ggraph geom_node_circle geom_node_text geom_edge_link label_rect 
#' @importFrom grid convertX convertY
#' @rdname designDiagram-class
#' @export
print.designDiagram <- function(x,...) {
  # Table of dimensions
  if (any(x$inner[upper.tri(x$inner)]!=0)) {
    cat("Non-orthogonal design with dimensions:\n")
  } else {
    cat("Orthogonal design with dimensions:\n")
  }
  print(rbind(Nparm=x$Nparm,df=x$df))
}


#' @rdname designDiagram-class
#' @export
summary.designDiagram <- function(x,...) {
  # Table of dimensions
  if (any(x$inner[upper.tri(x$inner)]!=0)) {
    cat("Non-orthogonal design with dimensions:\n")
  } else {
    cat("Orthogonal design with dimensions:\n")
  }
  print(rbind(Nparm=x$Nparm,df=x$df))
  
  # Table of inner products
  if (any(x$inner[upper.tri(x$inner)]!=0)) {
    cat("\n")
    cat("Note: Sum-of-Squares and p-values may depend on order of terms in an non-orthogonal design.\n")
    cat("\n")
    cat("Total inner products between subspaces (used to decide orthogonality):\n")
    print(x$inner)
  }
  
  # Table of relations
  cat("\n")
  cat("Table of relations:\n")
  print(x$relations)
  
  # Additional output if response is present
  cat("\n")
  if (!x$response) {
    cat("No response variable specified.\n")
  } else {
    cat("Type-I orthogonal decomposition of response variable:\n")
    print(rbind(SS=x$SS[1,],MSS=x$MSS[1,]))
    cat("\n")
    cat("P-values for F-tests against nested random effect:\n")
    print(signif(x$pvalue,6))
  }
}

#' @rdname designDiagram-class
#' @export
plot.designDiagram <- function(x,circle="none",pvalue=(circle=="MSS"),
                               kill=~1,ca=TRUE,
                               color=ifelse(circle=="MSS","lightblue","lightgreen"),
                               circle.scaling=1,
                               arrow.type=arrow(angle=20,length=unit(4,"mm")),
                               xlim=c(0,1),ylim=c(0,1),
                               horizontal=TRUE) {
  # data frame with edges 
  g.df <- data.frame(from=as.character(1+(which(x$relations=="<-")-1)%/%length(x$terms)),
                     to=as.character(1+(which(x$relations=="<-")-1)%%length(x$terms)),
                     pvalue=paste0("p=",signif(x$pvalue[x$relations=="<-"],digits=3)))
  g.df$pvalue[g.df$pvalue=="p=NA"] <- NA 
  
  # Sugiyama layout scaled in box specified by xlim and ylim
  g <- create_layout(g.df,"sugiyama")
  if (horizontal) {
    tmp <- g$x
    g$x <- -g$y
    g$y <- tmp
  }
  if (max(g$x)>min(g$x)) {
    g$x <- xlim[1] + (xlim[2]-xlim[1])*(g$x-min(g$x))/(max(g$x)-min(g$x))
  } else {
    g$x <- mean(xlim)
  }
  if (max(g$y)>min(g$y)) {
    g$y <- ylim[1] + (ylim[2]-ylim[1])*(g$y-min(g$y))/(max(g$y)-min(g$y))
  } else {
    g$y <- mean(ylim)
  }
  
  # Text labels
  g$text  <- paste0('"',x$terms,'"[',x$df,']^',x$Nparm)[as.numeric(g$name)]
  g$text0 <- paste0(x$terms,x$Nparm)[as.numeric(g$name)]

  # make graph
  p <- ggraph(g) + 
    geom_blank(aes(x=x-0.5*diff(xlim)*grid::convertX(unit(attr(label_rect(text0,fontsize=18),"width"),"cm"),"npc",valueOnly = TRUE),
                   y=y-0.5*diff(ylim)*grid::convertY(unit(attr(label_rect(text0,fontsize=18),"height"),"cm"),"npc",valueOnly = TRUE))) +
    geom_blank(aes(x=x+0.5*diff(xlim)*grid::convertX(unit(attr(label_rect(text0,fontsize=18),"width"),"cm"),"npc",valueOnly = TRUE),
                   y=y+0.5*diff(ylim)*grid::convertY(unit(attr(label_rect(text0,fontsize=18),"height"),"cm"),"npc",valueOnly = TRUE)))
  
  # Radii of circles
  if (is.element(circle,c("SS","MSS"))) {
    # terms that will have circles
    myterms <- setdiff(x$terms,attr(terms(kill,keep.order=TRUE),"term.labels"))
    if (attr(terms(kill),"intercept")==1) myterms <- setdiff(myterms,"1")

    # choose maximal radius
    max.r <- circle.scaling*0.5*sqrt(outer(g$x,g$x,"-")^2 + outer(g$y,g$y,"-")^2)
    max.r <- min(max.r[upper.tri(max.r)])
    
    # visualize collinearity analysis?
    if (ca) {
      # with collinearity analysis
      if (circle=="SS") {SS <- x$SS[,myterms,drop=FALSE]} else {SS <- x$MSS[,myterms,drop=FALSE]}
      ii <- apply(SS,2,function(y){min(which(diff(c(y[!is.na(y)],-1))<0))})
      # make legend
      variables <- setdiff(x$terms,setdiff(setdiff(x$terms,myterms),rownames(SS)))
      p <- p + geom_blank(aes(col=variable,fill=variable),data.frame(variable=factor(variables,levels=variables)))
      # filled bullseye
      for (i in max(ii):1) {
        mydf <- g[order(g$name),]
        mydf <- mydf[is.element(x$terms,myterms),]
        mydf <- mydf[ii>=i,]
        area <- SS[i,ii>=i]
        mydf$r <- max.r*sqrt(area/max(SS,na.rm=TRUE))
        if (i > 1) {
          mydf$variable <- factor(rownames(SS)[i],levels=variables)
        } else {
          mydf$variable <- factor(colnames(SS),levels=variables)
        }
        p <- p + geom_node_circle(aes(col=variable,fill=variable),data=mydf)
      }
      # circumference bullseye
      for (i in nrow(SS):2) {
        # TO DO: What is nrow(x$SS)=1 ??
        mydf <- g[order(g$name),]
        mydf <- mydf[is.element(x$terms,myterms),]
        mydf <- mydf[(i > ii) & (!is.na(SS[i,])),]
        if (nrow(mydf)>0) {
          area <- SS[i,(i > ii) & (!is.na(SS[i,]))]
          mydf$r <- max.r*sqrt(area/max(SS,na.rm=TRUE))
          mydf$variable <- factor(rownames(SS)[i],levels=variables)
          p <- p + geom_node_circle(aes(col=variable),data=mydf,lty=2,lwd=1.2)
        }
      }
      # coord fixed
      p <- p + coord_fixed()
    } else {
      # without collinearity analysis
      if (circle=="SS") {area <- x$SS[1,myterms]} else {area <- x$MSS[1,myterms]}
      mydf <- g[order(g$name),]
      mydf <- mydf[is.element(x$terms,myterms),]
      mydf$r <- max.r*sqrt(area/max(area,na.rm=TRUE))

      # add circles
      p <- p + geom_node_circle(aes(r=r),data=mydf,col=color,fill=color) +
        coord_fixed()
    }
  }

  # add term names, number of parameters and degrees of freedom
  p <- p + geom_node_text(aes(x=x,y=y,label=text),parse=TRUE)
  
  # add arrows
  p <- p + geom_edge_link(aes(start_cap=label_rect(node1.text0),
                              end_cap=label_rect(node2.text0)),
                          arrow=arrow.type)
  
  # add p-values
  if (pvalue) {
    p <- p + geom_label(aes(x=(xend+x)/2, 
                            y=(yend+y)/2 - diff(ylim)*grid::convertY(unit(4,"mm"),"npc",valueOnly=TRUE)*(yend==y), label=pvalue), get_edges(),
                        label.padding = unit(0.15,"lines"))
  }
  
  # return graph
  return(p)
}
